CadeMeuMedico/Controllers/MedicosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;
using CadeMeuMedico.Models;

namespace CadeMeuMedico.Controllers
{
    public class MedicosController : Controller
    {
        private EntidadesCadeMeuMedicoBD db = new EntidadesCadeMeuMedicoBD();
        
        //
        // GET: /Medicos/
        public ActionResult Index()
        {
            //var medicos = db.Medicos.Include(m => m.Cidade)
            //    .Include(m => m.Especialidade).ToList();
            var medicos = from m in db.Medicos.Include(m => m.Cidades)
                          select m;
            return View(medicos.ToList());
        }

        public ActionResult Adicionar()
        {
            ViewBag.IDCidade = new SelectList(db.Cidades, "IDCidade", "Nome");
            ViewBag.IDEspecialidade = new SelectList(db.Especialidades, "IDEspecialidade", "Nome");
            return View();
        }

        [HttpPost]
        public ActionResult Adicionar(Medicos medico)
        {
            if(ModelState.IsValid)
            {
                db.Medicos.Add(medico);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.IDCidade = new SelectList(db.Cidades, "IDCidade", "Nome");
            ViewBag.IDEspecialidade = new SelectList(db.Especialidades, "IDEspecialidade", "Nome");
            return View(medico);
        }

        public ActionResult Editar(long id)
        {
            Medicos medico = db.Medicos.Find(id);
            ViewBag.IDCidade = new SelectList(db.Cidades, "IDCidade", "Nome", medico.IDCidade);
            ViewBag.IDEspecialidade = new SelectList(db.Cidades, "IDEspecialidade", "Nome", medico.IDEspecialidade);
            return View(medico);
        }

        [HttpPost]
        public ActionResult Editar(Medicos medico)
        {
            if(ModelState.IsValid)
            {
                db.Entry(medico).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("index");
            }
            ViewBag.IDCidade = new SelectList(db.Cidades, "IDCidade", "Nome", medico.IDCidade);
            ViewBag.IDEspecialidade = new SelectList(db.Cidades, "IDEspecialidade", "Nome", medico.IDEspecialidade);
            return View(medico);
        }

        [HttpPost]
        public string Excluir(long id)
        {
            try
            {
                Medicos medico = db.Medicos.Find(id);
                db.Medicos.Remove(medico);
                db.SaveChanges();
                return Boolean.TrueString;
            }
            catch
            {
                return Boolean.FalseString;
            }
        }
    }
}

CadeMeuMedico/Views/Layout.cshtml
<!DOCTYPE html>

<html lang="pt-br">
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Cade meu medico? - @ViewBag.Title</title>
    <link href="@Url.Content("~/Content/bootstrap.css")" rel="stylesheet" />
    <style>
        body{
            padding-top: 60px;
        }
    </style>
</head>
<body>
    <nav class="navbar navbar-dark navbar-expand-sm bg-dark fixed-top">

        <div class="container">            
            <a class="navbar-brand" href="#">Cade meu medico?</a>           
            <div class="collapse navbar-collapse">
                <ul class="nav navbar-nav">
                    <li class="active"><a href="#"></a></li>
                    <li id="menuMedicos">
                        @Html.ActionLink("Médicos", "index", "Medicos", null, new {@class = "btn btn-dark"})
                    </li>
                    <li id="menuMedicos">
                        @Html.ActionLink("Cidades", "index", "Cidades", null, new {@class = "btn btn-dark"})
                    </li>
                    <li id="menuMedicos">
                        @Html.ActionLink("Especialidades", "index", "Especialidades", null, new { @class="btn btn-dark"} )
                    </li>
                </ul>
            </div>
        </div>    
    </nav>

    <div class="container">
        @RenderBody()
    </div>


    <script src="@Url.Content("~/Scripts/jquery-3.3.1.js")" ></script>
    <script src="@Url.Content("~/Scripts/bootstrap.js")"></script>
    @RenderSection("script", required: false)

</body>
</html>